### ISSUE TITLE
Room Core - Remember Extension Authorization

### ISSUE THREAD

**Issue by wwwizzarrdry** [RoonLabs/node-roon-api#10]
I've got my Room web playback controller working now. Nice work on the API, extremely easy to setup.

However, every time I start my node app, I have to re-authorize the extension on my roon core. What am I missing, in the Docs, that will tell Roon to remember my app between sessions and restarts?

I obviously shouldn't have to re-authorize every time I stop/start my node server.

**Comment by bcoburn3** [comment]
If everything is working correctly this should be totally automatic.  Extension state should be saved to a `config.json` file automatically when the extension connects to a Roon core.  By default I believe this is saved in the root of the directory you run the Node from.  Is that file getting saved?

**Comment by wwwizzarrdry** [comment]
Negative. There is no config being saved. I'll have to see why that is. Thanks for the tip.

Once the config was created, there were no more issues remembering auth. This issue is closed.
