### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by ChristianRiedl** [RoonLabs/node-roon-api#19]
I am working on a Roon Web Controller implemented as Progressive Web App. 
It requires to use the websocket based Roon API  via secured websockets (wss). 
Supporting only HTTP causes more and more troubles on current browsers. 
Would be great to support HTTPS !!!

**Comment by dannyfiresnake** [comment]
While `wss` may be possible, how do you propose an SSL certificate for the endpoint?

**Comment by dannyfiresnake** [comment]
oops!

**Comment by ChristianRiedl** [comment]
I agree, it only makes sense when Roon is running on an advanced server, hosting also a web site for example (as in my case). So it could be only an optional feature, probably required only by a minority of users. 
In the meanwhile I implemented a work arround, a wss=> ws relay integrated in a web server.

**Comment by dannyfiresnake** [comment]
a public web server? yikes

**Comment by ChristianRiedl** [comment]
A smarthome and media web server only for me and my family, of course with strong authentication :-)).

**Comment by nuclearpengy** [comment]
What about running Let's Encrypt/Certbot within the Roon OS?
I use Let's Encrypt certs on my local dev machine and it works like a charm using the "DNS challenge".

**Comment by dannyfiresnake** [comment]
The Roon API has to do with Roon, not Roon OS.

I agree that a WSS=>WS relay is the right thing. An ngrok or some other type of reverse proxy in front of it is the right thing to do here. HTTPS just doesn't work very well inside the home.
