### ISSUE TITLE
Feature request: Ability to sort and filter the browse api

### ISSUE THREAD

**Issue by mannp** [RoonLabs/node-roon-api#22]
Referencing the basic nature of the current browse api -> https://community.roonlabs.com/t/roon-web-controller-2-0-0-alpha-now-available/110504/41?u=mannp

We would welcome the ability to filter and sort the results of the browse api.

Thanks for your consideration.

**Comment by lkostrowski** [comment]
Bump - it is extremely hard to work with stateful api and there is very limited data. 

I would love to see some RESTful API with persistent IDs of tracks, albums etc for full experience

**Comment by dannyfiresnake** [comment]
feature requests should go on community.roonlabs.com in the feedback section.

**Comment by mannp** [comment]
> feature requests should go on community.roonlabs.com in the feedback section.

After 2 years its clearly a waste of time requesting this elsewhere.
