### ISSUE TITLE
Feature Request: API to read/write metadata

### ISSUE THREAD

**Issue by lightwave** [RoonLabs/node-roon-api#26]
There is currently no way to use API to programmatically update album/artist/track names or other metadata. Now, users have to make a minimum of 5 clicks to edit track title per track. For an album of 10 tracks, that's 50 clicks to update the track names.  External tagging application won't help with Tidal/Qobuz contents. The only way to override Tidal/qobuz album/track names is via the Roon UI which requires too many click.

**Comment by dannyfiresnake** [comment]
feature requests should go on community.roonlabs.com in the feedback section.
