### ISSUE TITLE
subscribe_zones callback broken

### ISSUE THREAD

**Issue by DrCWO** [RoonLabs/node-roon-api#27]
I encountered an issue with my rooDial after the latest roon server update
[Roon version 1.8 (build 790) stable (64Bit)].

To discover the zones and also the changes of the zones I use:

let transport = core.services.RoonApiTransport;
transport.subscribe_zones(function (cmd, data) {
my code goes here
}

Since the latest server update I did no more get any callback if a zone was added or removed. I get the callback only once, wenn I start rooDial. There I get the “Subscribed” cmd but never anything else.

It can be verified with the code at the end of this page: https://github.com/RoonLabs/node-roon-api

**Comment by dannyfiresnake** [comment]
do you have a test repo we can test again? I just wrote an extension and do not have this problem.

**Comment by DrCWO** [comment]
Hi Danny,
this is quite an old issue ;-)

After a reboot of the core (1.8) and a reboot of rooExtend anything was fine again.

Best DrCWO

**Comment by dannyfiresnake** [comment]
ok, thanks.
