### ISSUE TITLE
Now Playing info not consistent with Roon app(s)

### ISSUE THREAD

**Issue by CatalinMustata** [RoonLabs/node-roon-api#28]
I've noticed the info I get in the `now_playing` field is not consistent with the info displayed in the Roon App. Namely, I observed the data returned contains the band and every composer mentioned in the credits. However, if I look at the app it only lists performers.

Concrete example. I was playing `Confessions, Pt. 2` by `BadBadNotGood` and the Roon App displayed it as being played by `BadBadNotGood, Colit Stetson`. The data I received through the API had more information, but no succint version as the Roon app has.

```json
{
  "seek_position":130,
  "length":384,
  "one_line":{"line1":"Confessions, Pt. 2 - BadBadNotGood / Colin Stetson / Alexander Sowinski / Leland Whitty / Chester Hansen / Matthew Tavares"},
  "two_line":{"line1":"Confessions, Pt. 2","line2":"BadBadNotGood / Colin Stetson / Alexander Sowinski / Leland Whitty / Chester Hansen / Matthew Tavares"},
  "three_line":{"line1":"Confessions, Pt. 2","line2":"BadBadNotGood / Colin Stetson / Alexander Sowinski / Leland Whitty / Chester Hansen / Matthew Tavares","line3":"IV"
}
```

Is there any way to get a more succint version of this data?

**Comment by dannyfiresnake** [comment]
this now-playing information is meant to be displayed as is, not to be parsed out.
