### ISSUE TITLE
Feedback: snake_case vs camelCase

### ISSUE THREAD

**Issue by haysclark** [RoonLabs/node-roon-api#4]
I was curious why RoonLabs is using snake_case for their API instead of the more common camelCase convention?  The API feels like Ruby because of the snake_case.

**Comment by dannyfiresnake** [comment]
code generation tools from documentation -- we should probably fix this, but it'd be a breaking change..... i'll see what we can do.

**Comment by Khazul** [comment]
Something for a V2 API :)

**Comment by dannyfiresnake** [comment]
feature requests should go on community.roonlabs.com in the feedback section.
