### ISSUE TITLE
[Bug] Loop setting in API does not match Loop in Official Client

### ISSUE THREAD

**Issue by pluggemi** [RoonLabs/node-roon-api#5]
While adding support for Loop, Shuffle, and Auto Radio buttons in the roon-web-controller [1] extension, I noticed that the Loop status in the zone.settings array do not match the official client.  The status of "loop" and "loop_one" appear to be reversed from what the official clients on IOS and Mac show.

This one is correct:
Loop Disabled in Official Client
Array of the zone.settings
`{"loop":"disabled","shuffle":false,"auto_radio":false}`

These two are reversed:
Loop All in Official client
Array of the zone.settings
`{"loop":"loop_one","shuffle":false,"auto_radio":false}`

Loop One in Official Client
Array of the zone.settings
`{"loop":"loop","shuffle":false,"auto_radio":false}`

I checked the .js files in the node-roon-api and the node-api-transport projects, but did not see anything obvious.  So this may be getting returned from the core incorrectly.

The rest of the zone information correctly reflects the loop setting and I have a workaround in place in my client to take this into account.  But I wanted to pass this observation on.

[1] https://github.com/pluggemi/roon-web-controller

**Comment by pluggemi** [comment]
By the way, the commands in the transport.change_settings API call work correctly.  It appears to be isolated to the zone output array.

**Comment by blucz** [comment]
```
[master 393ecfff22] fix reversed loop/loop_one status
 1 file changed, 2 insertions(+), 2 deletions(-)
```

This fix should roll out with the next release of Roon.
