### ISSUE TITLE
Extension cannot recover from network failure

### ISSUE THREAD

**Issue by vvv-ca** [RoonLabs/node-roon-api#7]
Hi,
I have a basic extension running using the transport and source control services, however it seems that the extension is unable to recover from even a small network disruption.
I'm running on RPI3 over wifi and if the network re-connects or if the extension starts before the network is fully connected it does not seem to attempt to reconnect.
In the output, I can see that the ping messages just stop:

<- REQUEST 22 com.roonlabs.ping:1/ping 
-> COMPLETE 22 Success 
<- REQUEST 23 com.roonlabs.ping:1/ping 
-> COMPLETE 23 Success 

At the end of my extension I just have 
roon.start_discovery();
do I need to do something more to be able to handle network availability?

Thanks!

**Comment by bcoburn3** [comment]
The intent is that calling start_discovery() should be enough.  You should get core_paired/core_unpaired or core_lost/core_found events as appropriate if there are temporary network problems.

We obviously have a bug where that doesn't work currently, I have a plan to fix it and should be able to push something "soon"

**Comment by bcoburn3** [comment]
This should be fixed in commit ce349b4

We know attempt to rediscover every 1 minute and every time the available network interfaces change, so long as your extension isn't paired to a specific Roon core.

**Comment by vvv-ca** [comment]
Seems to work now, thanks!
