### ISSUE TITLE
Node 5.x compatibility broken

### ISSUE THREAD

**Issue by JanKoudijs** [RoonLabs/node-roon-api#8]
The latest [commit](https://github.com/RoonLabs/node-roon-api/commit/f0f48ab76690614b4ce0037c04f791bd9213f1fb) breaks the Node 5.x compatibility. It is the addition of a parameter default at line 74 of moo.js.

Was this overseen or is it the idea to increase the minimum Node version to 6.x?

I stumbled on this while performing tests on a Windows XP VM (using XP Embedded updates :) ). The latest Node version that runs on XP is 5.12.0.

**Comment by bcoburn3** [comment]
I will fix this, we didn't intend to break Node 5.x compatibility.

**Comment by bcoburn3** [comment]
I believe this to be fixed in commit 2578a44, I have tested at the level of confirming that ping works on node 5.12.0 using https://github.com/creationix/nvm under Ubuntu Linux

**Comment by JanKoudijs** [comment]
Yep, it's fixed.
Within an hour, you guys are impressive!

Thanks (also for the link to the test tool).
